language: r
sudo: true
cache: packages

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      r: devel
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

addons:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - imagemagick
      - jags

script:
- Rscript main.R
