language: r
sudo: true
cache: packages

r: 
  - oldrel
  - release
  - devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars
  - sudo apt-get -y install imagemagick jags r-cran-ncdf4 libudunits2-dev

script:
- Rscript main.R
