language: r
cache: packages

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  global:
    - MAKEFLAGS="-j 2"
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - clang-6.0
      - imagemagick
      - jags

script:
- Rscript main.R
