language: r
cache: packages

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - jags

script:
- Rscript main.R
