language: r
cache: packages

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir -p ~/.R/
  - echo "CXX = $CXX" >> ~/.R/Makevars
  - echo "CXX14 = $CXX" >> ~/.R/Makevars 
  - echo "CXX14FLAGS = `R CMD config CXXFLAGS` -pedantic -g0 -fPIC" >> ~/.R/Makevars 
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX =~ clang.* ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - echo ${CXX} --version
  - echo ${CLANG_EXTRA_ARG}

env:
  global:
    - MAKEFLAGS="-j 2"
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - imagemagick
      - jags

script:
- Rscript main.R
