language: r
cache: packages

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y "ppa:marutter/rrutter"
  - sudo add-apt-repository -y "ppa:marutter/c2d4u"
  - sudo apt-get update
  - sudo apt-get install r-cran-rstan

r:
  - oldrel
  - release
  - devel

addons:
    packages:
      - imagemagick
      - jags

script:
- Rscript main.R
