---
title: "Notes on shrinkage and prediction in hierarchical models"
description: |
  Partial pooling and the best NBA free throw shooters of all time.
author:
  - name: Maxwell B. Joseph
    url: {}
date: 2014-12-13
output:
  radix::radix_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Ecologists increasingly use mixed effects models, where some intercepts or 
slopes are fixed, and others are random (or varying).
Often, confusion exists around whether and when to use fixed vs. random 
intercepts/slopes, which is understandable given their 
[multiple definitions](http://andrewgelman.com/2005/01/25/why_i_dont_use/).

In an attempt to help clarify the utility of varying intercept models (and more 
generally, hierarchical modeling), specifically in terms of shrinkage and 
prediction, here is a 
[GitHub repo](https://github.com/mbjoseph/hierarchical_models) with materials 
and a slideshow from our department's graduate QDT (quantitative (th)ink tank) 
group.

For fun, I've included a toy
[example](https://github.com/mbjoseph/hierarchical_models/blob/master/R_examples/nba/nba_freethrows.R)
demonstrating the value of shrinkage when trying to rank NBA players by their 
free throw shooting ability, a situation with wildly varying amounts of 
information (free throw attempts) on each player.
The example admittedly is not ecological, and sensitive readers may replace free
throw attempts with prey capture attempts for topical consistency.
Many if not most ecological datasets suffer from similar issues, with varying 
amounts of information from different sites, species, individuals, etc., so 
even without considering predation dynamics of NBA players, the example's 
relevance should be immediate.
